2022-02-18 09:54:28.388 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 09:56:02.870 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:02:11.347 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:05:12.030 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:06:27.091 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:07:00.639 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:21:02.834 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:21:37.603 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:27:14.355 [main] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:27:15.516 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:27:23.522 [RMI TCP Connection(2)-192.168.77.1] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:27:27.405 [boundedElastic-1] WARN  traceId[] o.s.b.actuate.redis.RedisReactiveHealthIndicator:89 - Redis health check failed
org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:109)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1225)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1206)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedReactiveConnection(LettuceConnectionFactory.java:980)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:441)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:95)
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:85)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:225)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:234)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:207)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.lambda$null$0(LettucePoolingConnectionProvider.java:97)
	at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.create(ConnectionPoolSupport.java:209)
	at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.create(ConnectionPoolSupport.java:199)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:58)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:899)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:122)
	at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:117)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:103)
	... 15 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2022-02-18 10:31:17.962 [main] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:31:19.020 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:31:26.803 [RMI TCP Connection(2)-192.168.77.1] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:32:15.343 [main] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:32:17.321 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:32:26.239 [RMI TCP Connection(4)-192.168.77.1] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:33:10.332 [main] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:33:11.381 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:33:19.482 [RMI TCP Connection(9)-192.168.77.1] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:34:06.750 [main] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:34:07.786 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:34:16.092 [RMI TCP Connection(7)-192.168.77.1] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:37:39.207 [main] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:37:40.253 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 10:37:48.087 [RMI TCP Connection(1)-192.168.77.1] WARN  traceId[] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:37:58.815 [XNIO-1 task-1] WARN  traceId[7e3ba386-5bba-402e-b17c-3f366f3bd6be] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:38:17.746 [XNIO-1 task-1] WARN  traceId[9cf55f5e-7ad6-43fa-bc48-e264bfe97d86] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:38:24.668 [XNIO-1 task-1] WARN  traceId[d2af55ae-ad50-4374-ac68-9b8767feccac] o.s.c.c.client.ConfigServicePropertySourceLocator:140 - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2022-02-18 10:41:39.062 [main] WARN  traceId[] io.undertow.websockets.jsr:68 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-02-18 14:59:07.337 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447174
2022-02-18 14:59:07.338 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447192
2022-02-18 14:59:07.338 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447206
2022-02-18 14:59:07.339 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447220
2022-02-18 14:59:07.340 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447234
2022-02-18 14:59:07.341 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447247
2022-02-18 14:59:07.342 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447260
2022-02-18 14:59:07.343 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447273
2022-02-18 14:59:07.344 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447288
2022-02-18 14:59:07.344 [XNIO-1 task-1] WARN  traceId[261d88c7-d72b-4dd3-94ac-48bafcfda68d] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 15447303
2022-02-18 17:04:58.296 [XNIO-1 task-6] WARN  traceId[] o.s.w.s.m.support.DefaultHandlerExceptionResolver:199 - Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2022-02-18 17:05:14.560 [XNIO-1 task-6] WARN  traceId[94aae673-0eca-46ce-8642-229798c5e418] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 7567180
2022-02-18 17:07:04.703 [XNIO-1 task-6] WARN  traceId[4fb1ed53-5c44-4011-a640-4a5d1b0a20ae] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 110110
2022-02-18 17:09:13.989 [XNIO-1 task-6] WARN  traceId[34e42a01-0769-43d4-aeeb-ab0cc95a5988] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 129257
2022-02-18 17:11:04.687 [XNIO-1 task-6] WARN  traceId[0f1b39e7-28e1-46c5-ac35-31c337b20600] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 110678
2022-02-18 17:16:38.592 [XNIO-1 task-6] WARN  traceId[d86ac70b-35b6-4881-89f6-5609e1a9a799] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 278063
2022-02-18 17:18:28.338 [XNIO-1 task-6] WARN  traceId[1ad00ffd-f6fc-4408-8a7b-c594a0c7bf42] o.s.w.s.m.support.DefaultHandlerExceptionResolver:199 - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Invalid UTF-8 start byte 0xbd; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0xbd
 at [Source: (PushbackInputStream); line: 27, column: 26] (through reference chain: com.example.demo.vo.TopicManageVO["option_item"]->java.util.ArrayList[3])]
2022-02-18 17:18:38.689 [XNIO-1 task-6] WARN  traceId[d4ae0478-6724-47c0-b803-c0feb8b0459c] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 61014
2022-02-18 17:20:12.091 [XNIO-1 task-6] WARN  traceId[3b92f94e-a96c-45bb-9fc9-5ae56beec07b] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 93373
2022-02-18 17:23:38.403 [XNIO-1 task-6] WARN  traceId[a6c06d01-6667-4369-905f-023049bf91b1] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 110643
2022-02-18 17:25:28.635 [XNIO-1 task-6] WARN  traceId[ccf98fd9-7808-49c1-aa19-9af74989216e] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 110204
2022-02-18 17:27:26.203 [XNIO-1 task-6] WARN  traceId[0b454dba-fdff-44e1-8f7b-49bcb7d47cc1] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 117546
2022-02-18 17:29:06.639 [XNIO-1 task-6] WARN  traceId[5a6edf6e-beb9-4e81-abfc-1ef3f5f784ea] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 100409
2022-02-18 17:30:35.144 [XNIO-1 task-6] WARN  traceId[1c50e294-8407-4038-8d56-02f0aca3c02c] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 88477
2022-02-18 17:33:02.822 [XNIO-1 task-6] WARN  traceId[aaeefca7-387d-4823-ba70-ff12cf7c1401] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 147651
2022-02-18 17:34:33.042 [XNIO-1 task-6] WARN  traceId[2bd77392-e7ee-44e2-a8dd-c925a1addce8] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 90193
2022-02-18 17:45:22.055 [XNIO-1 task-6] WARN  traceId[43a4f9f8-4d8c-4c07-aea3-0b7920d084cb] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 648984
2022-02-18 17:49:08.369 [XNIO-1 task-6] WARN  traceId[3784491f-2a5d-4ed1-894f-571e3dfd5286] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 226283
2022-02-18 17:55:03.150 [XNIO-1 task-6] WARN  traceId[ceb1b370-76ee-43bc-b885-797d30cce7da] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 354737
2022-02-18 17:57:16.813 [XNIO-1 task-6] WARN  traceId[cbab4fd0-52f2-42cd-9f29-7110ed03c2ac] com.alibaba.druid.pool.DruidAbstractDataSource:1494 - discard long time none received connection. , jdbcUrl : jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, version : 1.2.5, lastPacketReceivedIdleMillis : 133643
